# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesala',
            name='begin',
            field=models.DateTimeField(verbose_name='Begining'),
        ),
        migrations.AlterField(
            model_name='moviesala',
            name='end',
            field=models.DateTimeField(verbose_name='End'),
        ),
    ]
